export type Vehicle = {
  id: string;
  name: string;
  type: "motorcycle" | "car" | "minibus";
  price: string;
  status: "Available" | "Booked";
  image: string;
  drive: string;
  fuel: string;
  seat: string;
  description: string;
};

export const vehicles: Vehicle[] = [
  // --- MOTORCYCLES ---
  {
    id: "honda-vario",
    name: "Honda Vario",
    type: "motorcycle",
    price: "110rb / Day",
    status: "Available",
    image: "/images/vehicles/vario.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "2 Seat",
    description: "Motor matic yang bertenaga dan nyaman untuk keliling kota.",
  },
  {
    id: "honda-beat-street",
    name: "Honda Beat Street",
    type: "motorcycle",
    price: "90rb / Day",
    status: "Available",
    image: "/images/vehicles/beat-street.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "2 Seat",
    description: "Tampil gaya dengan stang telanjang, cocok untuk anak muda.",
  },
  {
    id: "yamaha-nmax",
    name: "Yamaha NMAX",
    type: "motorcycle",
    price: "150rb / Day",
    status: "Available",
    image: "/images/vehicles/nmax.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "2 Seat",
    description: "Skuter bongsor yang stabil dan nyaman untuk perjalanan jauh.",
  },
  {
    id: "honda-pcx",
    name: "Honda PCX",
    type: "motorcycle",
    price: "160rb / Day",
    status: "Available",
    image: "/images/vehicles/pcx.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "2 Seat",
    description: "Kemewahan dan kenyamanan maksimal dalam berkendara.",
  },
  {
    id: "honda-scoopy",
    name: "Honda Scoopy",
    type: "motorcycle",
    price: "110rb / Day",
    status: "Available",
    image: "/images/vehicles/scoopy.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "2 Seat",
    description: "Desain retro modern yang ikonik dan irit bahan bakar.",
  },
  {
    id: "honda-stylo",
    name: "Honda Stylo",
    type: "motorcycle",
    price: "145rb / Day",
    status: "Available",
    image: "/images/vehicles/stylo.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "2 Seat",
    description: "Skuter fashionable dengan performa mesin yang mumpuni.",
  },

  // --- CARS ---
  {
    id: "toyota-agya",
    name: "Toyota Agya",
    type: "car",
    price: "250rb / Day",
    status: "Available",
    image: "/images/vehicles/agya.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "5 Seat",
    description: "Mobil city car yang lincah dan sangat mudah dikendarai.",
  },
  {
    id: "honda-brio",
    name: "Honda Brio",
    type: "car",
    price: "275rb / Day",
    status: "Available",
    image: "/images/vehicles/new-brio.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "5 Seat",
    description: "Compact car dengan performa mesin terbaik di kelasnya.",
  },
  {
    id: "honda-mobilio",
    name: "Honda Mobilio",
    type: "car",
    price: "300rb / Day",
    status: "Available",
    image: "/images/vehicles/mobilio.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "7 Seat",
    description: "MPV keluarga dengan kabin luas dan bagasi fleksibel.",
  },
  {
    id: "toyota-avanza",
    name: "Toyota Grand Avanza",
    type: "car",
    price: "300rb / Day",
    status: "Available",
    image: "/images/vehicles/g-avanza.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "7 Seat",
    description: "Mobil sejuta umat yang tangguh untuk segala medan.",
  },
  {
    id: "honda-jazz",
    name: "Honda Jazz",
    type: "car",
    price: "350rb / Day",
    status: "Available",
    image: "/images/vehicles/jazz.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "5 Seat",
    description: "Hatchback sporty dengan fitur ultra seat yang praktis.",
  },
  {
    id: "daihatsu-xenia",
    name: "Daihatsu New Xenia",
    type: "car",
    price: "350rb / Day",
    status: "Available",
    image: "/images/vehicles/xenia.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "7 Seat",
    description: "Sahabat keluarga yang andal dan efisien bahan bakar.",
  },
  {
    id: "mitsubishi-xpander",
    name: "Mitsubishi Xpander",
    type: "car",
    price: "400rb / Day",
    status: "Available",
    image: "/images/vehicles/xpander.png",
    drive: "Self Drive",
    fuel: "Petrol",
    seat: "7 Seat",
    description: "Desain tangguh ala SUV dengan kenyamanan MPV mewah.",
  },

  // --- MINIBUS & BUS ---
  {
    id: "toyota-hiace",
    name: "Toyota Hiace",
    type: "minibus",
    price: "1.25jt / Day",
    status: "Available",
    image: "/images/vehicles/hiace.png",
    drive: "With Driver",
    fuel: "Diesel",
    seat: "14 Seat",
    description: "Kabin sangat luas, cocok untuk travel grup atau keluarga besar.",
  },
  {
    id: "isuzu-elf-short",
    name: "Isuzu Elf Short",
    type: "minibus",
    price: "1.2jt / Day",
    status: "Available",
    image: "/images/vehicles/elf-short.png",
    drive: "With Driver",
    fuel: "Diesel",
    seat: "12 Seat",
    description: "Pilihan utama untuk transportasi rombongan wisata.",
  },
  {
    id: "big-bus",
    name: "Big Bus Luxury",
    type: "minibus", 
    price: "1.5jt / Day",
    status: "Available",
    image: "/images/vehicles/big-bus.png",
    drive: "With Driver",
    fuel: "Diesel",
    seat: "45-50 Seat",
    description: "Bus pariwisata eksekutif untuk perjalanan rombongan besar.",
  },
];